In [120]:
from utils import get_current_dir
import pandas as pd

inputpath = get_current_dir().parent / "data" / "artvis_cleaned.csv"
df = pd.read_csv(inputpath)

df = df.replace("null", pd.NA)
display(df.head())


df["a.id"] = df["a.id"].astype("Int64")
df = df.dropna(subset=["a.id"])

df["a.firstname"] = df["a.firstname"].astype("string")
df["a.firstname"] = df["a.firstname"].fillna("Unknown Firstname")

df["a.lastname"] = df["a.lastname"].astype("string")
df["a.lastname"] = df["a.lastname"].fillna("Unknown Lastname")

df["a.gender"] = pd.Categorical(df["a.gender"]).add_categories("Unknown Gender")
df["a.gender"] = df["a.gender"].fillna("Unknown Gender")

df["a.birthdate"] = pd.to_datetime(df["a.birthdate"], errors="coerce")

df["a.deathdate"] = pd.to_datetime(df["a.deathdate"], errors="coerce")

df["a.birthplace"] = df["a.birthplace"].astype("string")
df["a.birthplace"] = df["a.birthplace"].fillna("Unknown Birthplace")

df["a.deathplace"] = df["a.deathplace"].astype("string")
df["a.deathplace"] = df["a.deathplace"].fillna("Unknown Deathplace")

df["a.nationality"] = df["a.nationality"].astype("string")
df["a.nationality"] = df["a.nationality"].fillna("Unknown Nationality")

df["e.id"] = df["e.id"].astype("Int64")
df = df.dropna(subset=["e.id"])

df["e.title"] = df["e.title"].astype("string")
df["e.title"] = df["e.title"].fillna("Unknown Title")

df["e.venue"] = df["e.venue"].astype("string")
df["e.venue"] = df["e.venue"].fillna("Unknown Venue")

df["e.startdate"] = df["e.startdate"].astype("Int64")
df["e.startdate"] = df["e.startdate"].fillna(0)

df["e.type"] = pd.Categorical(df["e.type"]).add_categories("Unknown Type")
df["e.type"] = df["e.type"].fillna("Unknown Type")

df["e.paintings"] = df["e.paintings"].astype("Int64")
df["e.paintings"] = df["e.paintings"].fillna(0)

df["e.country"] = df["e.country"].astype("string")
df["e.country"] = df["e.country"].fillna("Unknown Country")

df["e.city"] = df["e.city"].astype("string")
df["e.city"] = df["e.city"].fillna("Unknown City")

df["e.latitude"] = df["e.latitude"].astype("float64")
df["e.latitude"] = df["e.latitude"].fillna(0)

df["e.longitude"] = df["e.longitude"].astype("float64")
df["e.longitude"] = df["e.longitude"].fillna(0)


print(df.head())
for col in df.columns:
    print(f"column: {col}, type: {df[col].dtype}, unique values: {df[col].nunique()}, null values: {df[col].isnull().sum()}")

,a.id,a.firstname,a.lastname,a.gender,a.birthdate,a.deathdate,a.birthplace,a.deathplace,a.nationality,e.id,e.title,e.venue,e.startdate,e.type,e.paintings,e.country,e.city,e.latitude,e.longitude
0,1,William Bernard,Adeney,M,1878-01-01,1966-01-01,London,London,GB,618,Exhibition of the Camden Town Group and Others,Public Art Galleries,1913,group,6,GB,Brighton,50.833333,-0.150000
1,1,William Bernard,Adeney,M,1878-01-01,1966-01-01,London,London,GB,720,The Second Exhibition of Works by Members of t...,Goupil Gallery,1915,group,4,GB,London,51.514248,-0.093145
2,1,William Bernard,Adeney,M,1878-01-01,1966-01-01,London,London,GB,729,Third Exhibition of Works by Members of the Lo...,Goupil Gallery,1915,group,5,GB,London,51.514248,-0.093145
3,1,William Bernard,Adeney,M,1878-01-01,1966-01-01,London,London,GB,650,The First Exhibition of Works by Members of Th...,Goupil Gallery,1914,group,5,GB,London,51.514248,-0.093145
4,1,William Bernard,Adeney,M,1878-01-01,1966-01-01,London,London,GB,680,Twentieth Century Art. A Review of Modern Move...,Whitechapel Art Gallery,1914,group,3,GB,London,51.514248,-0.093145

   a.id      a.firstname a.lastname a.gender a.birthdate a.deathdate  \
0     1  William Bernard     Adeney        M  1878-01-01  1966-01-01
1     1  William Bernard     Adeney        M  1878-01-01  1966-01-01
2     1  William Bernard     Adeney        M  1878-01-01  1966-01-01
3     1  William Bernard     Adeney        M  1878-01-01  1966-01-01
4     1  William Bernard     Adeney        M  1878-01-01  1966-01-01

  a.birthplace a.deathplace a.nationality  e.id  \
0       London       London            GB   618
1       London       London            GB   720
2       London       London            GB   729
3       London       London            GB   650
4       London       London            GB   680

                                             e.title                  e.venue  \
0     Exhibition of the Camden Town Group and Others     Public Art Galleries
1  The Second Exhibition of Works by Members of t...           Goupil Gallery
2  Third Exhibition of Works by Members of the Lo...           Goupil Gallery
3  The First Exhibition of Works by Members of Th...           Goupil Gallery
4  Twentieth Century Art. A Review of Modern Move...  Whitechapel Art Gallery

   e.startdate e.type  e.paintings e.country    e.city  e.latitude  \
0         1913  group            6        GB  Brighton   50.833333
1         1915  group            4        GB    London   51.514248
2         1915  group            5        GB    London   51.514248
3         1914  group            5        GB    London   51.514248
4         1914  group            3        GB    London   51.514248

   e.longitude
0    -0.150000
1    -0.093145
2    -0.093145
3    -0.093145
4    -0.093145
column: a.id, type: Int64, unique values: 11941, null values: 0
column: a.firstname, type: string, unique values: 5236, null values: 0
column: a.lastname, type: string, unique values: 9941, null values: 0
column: a.gender, type: category, unique values: 3, null values: 0
column: a.birthdate, type: datetime64[ns], unique values: 165, null values: 5674
column: a.deathdate, type: datetime64[ns], unique values: 213, null values: 5644
column: a.birthplace, type: string, unique values: 3413, null values: 0
column: a.deathplace, type: string, unique values: 2404, null values: 0
column: a.nationality, type: string, unique values: 55, null values: 0
column: e.id, type: Int64, unique values: 903, null values: 0
column: e.title, type: string, unique values: 850, null values: 0
column: e.venue, type: string, unique values: 295, null values: 0
column: e.startdate, type: Int64, unique values: 14, null values: 0
column: e.type, type: category, unique values: 3, null values: 0
column: e.paintings, type: Int64, unique values: 151, null values: 0
column: e.country, type: string, unique values: 21, null values: 0
column: e.city, type: string, unique values: 79, null values: 0
column: e.latitude, type: float64, unique values: 76, null values: 0
column: e.longitude, type: float64, unique values: 78, null values: 0

In [110]:
outputpath = get_current_dir().parent / "pages"

# Plotly

In [127]:
import pandas as pd
import plotly.express as px

df["e.startdate"] = pd.to_datetime(df["e.startdate"], format="%Y")
unique_years = df["e.startdate"].dt.year.unique()
print("Unique Years:", unique_years)

df_grouped = df.groupby(['e.startdate', 'e.latitude', 'e.longitude']).agg({
    'e.paintings': 'sum',
    'e.title': 'first',
    'e.type': 'first'
}).reset_index()

fig = px.scatter_geo(
    df_grouped,
    lat="e.latitude",
    lon="e.longitude",
    color="e.type",
    size="e.paintings",
    hover_name="e.title",
    animation_frame=df_grouped["e.startdate"].dt.year,
    title="Art Exhibition Locations Over Time",
    projection="natural earth",
    size_max=30,
)

if hasattr(fig.layout, 'sliders') and len(fig.layout.sliders) > 0:
    fig.layout.sliders[0].currentvalue.prefix = "Year: "
else:
    print("No sliders were created.")

fig.update_geos(
    showcoastlines=False,
    coastlinecolor="Black",
    showland=True,
    landcolor="LightGray",
    showocean=False,
    oceancolor="LightBlue",
    showcountries=True,
    countrycolor="Black"
)

fig.update_layout(
    title_x=0.5,
    geo=dict(
        scope="world",
        showframe=True,
        projection_type="natural earth"
    )
)

fig.write_html(str(outputpath / "animation.html"), full_html=True, include_plotlyjs="cdn")

Unique Years: [1913 1915 1914 1912 1910 1911 1909 1907 1906 1905 1908 1904 1902 1903]

# Ignore

In [5]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

location_data = df.groupby(["e.city", "e.latitude", "e.longitude", "e.startdate"])["e.paintings"].sum().reset_index()

fig = go.Figure()

fig.add_trace(go.Scattergeo(lon=location_data["e.longitude"], lat=location_data["e.latitude"], text=location_data.apply(lambda x: f"City: {x['e.city']}<br>" f"Year: {int(x['e.startdate'])}<br>" f"Paintings: {int(x['e.paintings'])}", axis=1), mode="markers", marker=dict(size=location_data["e.paintings"].apply(lambda x: min(x / 10, 50)), color=location_data["e.paintings"], colorscale="Viridis", showscale=True, colorbar=dict(title="Number of Paintings"), opacity=0.8), name="Exhibitions"))

fig.update_layout(
    title="Art Exhibitions Over Time",
    geo=dict(
        scope="europe",
        projection_type="mercator",
        showland=True,
        landcolor="rgb(243, 243, 243)",
        countrycolor="rgb(204, 204, 204)",
        showocean=True,
        oceancolor="rgb(230, 230, 250)",
        showcountries=True,
    ),
    updatemenus=[{"buttons": [{"args": [None, {"frame": {"duration": 1000, "redraw": True}, "fromcurrent": True}], "label": "Play", "method": "animate"}, {"args": [[None], {"frame": {"duration": 0, "redraw": True}, "mode": "immediate", "transition": {"duration": 0}}], "label": "Pause", "method": "animate"}], "direction": "left", "pad": {"r": 10, "t": 87}, "showactive": False, "type": "buttons", "x": 0.1, "y": 0}],
    sliders=[{"currentvalue": {"prefix": "Year: "}, "pad": {"t": 50}, "steps": [{"args": [[str(year)], {"frame": {"duration": 0, "redraw": True}, "mode": "immediate", "transition": {"duration": 0}}], "label": str(year), "method": "animate"} for year in sorted(location_data["e.startdate"].unique())]}],
)

frames = [
    go.Frame(
        data=[
            go.Scattergeo(
                lon=location_data[location_data["e.startdate"] == year]["e.longitude"],
                lat=location_data[location_data["e.startdate"] == year]["e.latitude"],
                text=location_data[location_data["e.startdate"] == year].apply(lambda x: f"City: {x['e.city']}<br>" f"Year: {int(x['e.startdate'])}<br>" f"Paintings: {int(x['e.paintings'])}", axis=1),
                mode="markers",
                marker=dict(size=location_data[location_data["e.startdate"] == year]["e.paintings"].apply(lambda x: min(x / 10, 50)), color=location_data[location_data["e.startdate"] == year]["e.paintings"], colorscale="Viridis", showscale=True, colorbar=dict(title="Number of Paintings"), opacity=0.8),
            )
        ],
        name=str(year),
    )
    for year in sorted(location_data["e.startdate"].unique())
]

fig.frames = frames

# include js
# fig.write_html(str(outputpath / "animation.html"), full_html=True, include_plotlyjs="cdn")

In [ ]:
import altair as alt
import pandas as pd

alt.data_transformers.enable("vegafusion")

location_stats = df.groupby(["e.country", "e.city"]).agg({"e.id": "count", "e.paintings": "sum", "e.venue": "nunique", "e.latitude": "first", "e.longitude": "first"}).reset_index()
location_stats.columns = ["country", "city", "num_exhibitions", "total_paintings", "unique_venues", "latitude", "longitude"]

width = 800
height = 300

brush = alt.selection_interval()

# Base map layer using a world map dataset
base_map = alt.Chart(alt.topo_feature("https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json", "countries")).mark_geoshape(fill="lightgray", stroke="white").properties(width=width, height=height).project("equirectangular")

# Exhibition locations layer
map_chart = (
    alt.Chart(location_stats)
    .mark_circle()
    .encode(longitude="longitude:Q", latitude="latitude:Q", size=alt.Size("num_exhibitions:Q", scale=alt.Scale(range=[50, 1000]), title="Number of Exhibitions"), color=alt.condition(brush, "country:N", alt.value("lightgray")), tooltip=[alt.Tooltip("country:N", title="Country"), alt.Tooltip("city:N", title="City"), alt.Tooltip("num_exhibitions:Q", title="Number of Exhibitions"), alt.Tooltip("total_paintings:Q", title="Total Paintings"), alt.Tooltip("unique_venues:Q", title="Number of Venues")])
    .properties(width=width, height=height, title="Exhibition Locations")
    .add_selection(brush)
)

# Combine base map and locations
combined_map = alt.layer(base_map, map_chart)

country_chart = alt.Chart(location_stats).mark_bar().encode(x=alt.X("country:N", sort="-y", title="Country"), y=alt.Y("sum(num_exhibitions):Q", title="Number of Exhibitions"), color=alt.condition(brush, "country:N", alt.value("lightgray")), tooltip=[alt.Tooltip("country:N", title="Country"), alt.Tooltip("sum(num_exhibitions):Q", title="Total Exhibitions"), alt.Tooltip("sum(total_paintings):Q", title="Total Paintings")]).properties(width=width, height=height // 2).transform_filter(brush)

scatter_chart = (
    alt.Chart(location_stats)
    .mark_circle(opacity=0.7)
    .encode(
        x=alt.X("num_exhibitions:Q", title="Number of Exhibitions"),
        y=alt.Y("total_paintings:Q", title="Total Paintings"),
        color=alt.condition(brush, "country:N", alt.value("lightgray")),
        size=alt.Size("unique_venues:Q", scale=alt.Scale(range=[50, 400]), title="Number of Venues"),
        tooltip=[alt.Tooltip("country:N", title="Country"), alt.Tooltip("city:N", title="City"), alt.Tooltip("num_exhibitions:Q", title="Number of Exhibitions"), alt.Tooltip("total_paintings:Q", title="Total Paintings"), alt.Tooltip("unique_venues:Q", title="Number of Venues")],
    )
    .properties(width=width, height=height // 2)
    .transform_filter(brush)
)

final_visualization = alt.vconcat(combined_map, alt.hconcat(country_chart, scatter_chart)).configure_view(stroke=None).configure_title(fontSize=20, anchor="middle")

# final_visualization.save(outputpath / "alt-v1.html")

In [19]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

fig = go.Figure()

fig.add_trace(
    go.Scattergeo(lon=df["e.longitude"], lat=df["e.latitude"], text=df.apply(lambda row: f"Exhibition: {row['e.title']}<br>" f"Venue: {row['e.venue']}<br>" f"City: {row['e.city']}<br>" f"Paintings: {row['e.paintings']}<br>" f"Year: {int(row['e.startdate'])}", axis=1), mode="markers", marker=dict(size=df["e.paintings"], sizeref=2.0 * max(df["e.paintings"]) / (40.0**2), sizemin=4, color=df["e.startdate"], colorscale="Viridis", showscale=True, colorbar=dict(title="Year")), hoverinfo="text")
)

fig.update_layout(
    title="Art Exhibitions Over Time",
    geo=dict(scope="europe", showland=True, landcolor="rgb(243, 243, 243)", countrycolor="rgb(204, 204, 204)", showocean=True, oceancolor="rgb(230, 230, 250)", projection_type="mercator"),
    updatemenus=[{"buttons": [{"args": [None, {"frame": {"duration": 500, "redraw": True}, "fromcurrent": True, "transition": {"duration": 300, "easing": "quadratic-in-out"}}], "label": "▶", "method": "animate"}, {"args": [[None], {"frame": {"duration": 0, "redraw": True}, "mode": "immediate", "transition": {"duration": 0}}], "label": "⏸", "method": "animate"}], "direction": "left", "pad": {"r": 10, "t": 87}, "showactive": False, "type": "buttons", "x": 0.1, "y": 0}],
    sliders=[
        {
            "active": 0,
            "yanchor": "top",
            "xanchor": "left",
            "currentvalue": {"font": {"size": 20}, "prefix": "Year: ", "visible": True, "xanchor": "right"},
            "transition": {"duration": 300, "easing": "cubic-in-out"},
            "pad": {"b": 10, "t": 50},
            "len": 0.9,
            "x": 0.1,
            "y": 0,
            "steps": [{"args": [[f"frame_{year}"], {"frame": {"duration": 300, "redraw": True}, "mode": "immediate", "transition": {"duration": 300}}], "label": str(year), "method": "animate"} for year in sorted(df["e.startdate"].unique())],
        }
    ],
)

frames = [
    go.Frame(
        data=[
            go.Scattergeo(
                lon=df[df["e.startdate"] == year]["e.longitude"],
                lat=df[df["e.startdate"] == year]["e.latitude"],
                text=df[df["e.startdate"] == year].apply(lambda row: f"Exhibition: {row['e.title']}<br>" f"Venue: {row['e.venue']}<br>" f"City: {row['e.city']}<br>" f"Paintings: {row['e.paintings']}<br>" f"Year: {int(row['e.startdate'])}", axis=1),
                mode="markers",
                marker=dict(size=df[df["e.startdate"] == year]["e.paintings"], sizeref=2.0 * max(df["e.paintings"]) / (40.0**2), sizemin=4, color=df[df["e.startdate"] == year]["e.startdate"], colorscale="Viridis", showscale=True, colorbar=dict(title="Year")),
                hoverinfo="text",
            )
        ],
        name=f"frame_{year}",
    )
    for year in sorted(df["e.startdate"].unique())
]

fig.frames = frames

# fig.write_html(str(outputpath / "plotly-v2.html"))